alert_threshold: 4
book_conf: 0.4
calculator_conf: 0.45
class_conf:
  book: 0.4
  calculator: 0.45
  earphone: 0.45
  person: 0.55
  phone: 0.5
  smartwatch: 0.5
classes:
- person
- phone
- book
- earphone
- calculator
- notebook
- smartwatch
detector_conf: 0.4
detector_merge_mode: wbf
detector_merge_nms: true
detector_nms_iou: 0.45
detector_primary: yolo11m.pt
detector_secondary: models/model_bestV3.pt
earphone_conf: 0.45
exam_policy:
  allow_book: false
  allow_calculator: false
  allow_earphones: false
  allow_notebook: false
gaze_confidence_threshold: 0.7
gaze_duration_threshold: 2.5
person_conf: 0.55
phone_conf: 0.5
repeat_dir_threshold: 4
repeat_window_sec: 12.0
weights:
  book: 4
  calculator: 4
  earphone: 6
  gaze_off_per_sec: 1
  notebook: 5
  person: 7
  phone: 8
  repetitive_head: 3
  smartwatch: 6
